[package]
authors = ["Arash Sal Moslehian <arashsm79@yahoo.com>"]
edition = "2020"
# If you change the name here, you must also do it in flake.nix
name = "jadeswarm"
version = "0.1.0"


[dependencies]
